name: Tests
on:
  workflow_call:


jobs:
  tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: true
      matrix:
        laravel: [ '12.*', '13.*' ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: '12.*'
            testbench: '^10.0'
          - laravel: '13.*'
            testbench: '^11.0'

    name: Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests
        run: composer test
